version = 0.1

[default.deploy.parameters]
stack_name = "food-delivery-backend"
resolve_s3 = true
s3_prefix = "food-delivery-backend"
region = "us-east-1"
confirm_changeset = false
capabilities = "CAPABILITY_IAM"
